fix: correct field name
trustification/trustify-ui pull request #101
Opened 2024-07-05 08:37 UTC by ctron

This will also be fixed on the backend side.

2024-07-05 08:54 UTC, ctron commented
Ok, looks like it takes a bit more. @carlosthe19916 maybe you can finish this up, or start from scratch with this is a pointer.

2024-07-05 09:01 UTC, gildub requested changes
The field name needs to be changed in `./src/app/pages/importer-list/importer-list.tsx`./src/app/pages/importer-list/importer-list.tsx too.

2024-07-05 09:01 UTC, gildub commented on client/src/app/api/models.ts
>    report: {
While at it, why not use interface definition for report instead ?
```ts
export interface ImporterReport {
  id: string;
  error?: string;
  report: ImporterReportDetails;
}
```

2024-07-08 15:29 UTC, carlosthe19916 commented
@gildub I pushed a commit to this branch to fix the missing change on ./src/app/pages/importer-list/importer-list.tsx .

2024-07-08 15:29 UTC, carlosthe19916 approved these changes

2024-07-09 14:33 UTC, merged