Add aria-label to some <Th>
trustification/trustify-ui pull request #103
Opened 2024-07-05 14:23 UTC by gildub

Fix https://github.com/trustification/trustify-ui/issues/96

2024-07-08 16:08 UTC, carlosthe19916 requested changes

2024-07-08 16:08 UTC, carlosthe19916 commented on client/src/app/pages/sbom-list/sbom-list.tsx
> +                  />
Although nice to have, your proposed change at `client/src/app/components/TableControls/TableHeaderContentWithControls.tsx` is fully solving the original issue, don't you think it is not necessary to add these changes? Some in the file below.

2024-07-08 16:08 UTC, carlosthe19916 commented on client/src/app/pages/sbom-list/sbom-list.tsx
> +              />
same here, there should be no need to add aria-label. 
If we start adding `aria-label` to one, then we might need to add it everywhere and although looks lazy I think we could avoid adding things and keep it simple unless required

2024-07-09 14:26 UTC, gildub commented on client/src/app/components/TableControls/TableHeaderContentWithControls.tsx
> +        <Th aria-label="before-data-{i}" key={i} />
@carlosthe19916, come-on, my approach was original isn't and it works. But let's change it to stick with common practices.

2024-07-09 14:28 UTC, gildub commented on client/src/app/components/TableControls/TableHeaderContentWithControls.tsx
>    </>
@carlosthe19916, yes I agree as not only it works too but this is a case of hidden Th content.

2024-07-10 14:00 UTC, carlosthe19916 approved these changes

2024-07-10 14:01 UTC, merged