fix: Importer reports: use API order
trustification/trustify-ui pull request #112
Opened 2024-07-17 08:32 UTC by gildub

Remove unnecessary sorting importers reports when managing the items in `useLocalTableControls`.
Although sorting out reports using only the `startDate` should be enough and using both start and end dates are likely to break the original order therefore as the API is already providing the reports in timely fashioned order then there is no need to reorder the items.

Before: 
![image](https://github.com/user-attachments/assets/9a911c5a-f86f-4ef6-bde1-c00183c7c390)

After: 
![image](https://github.com/user-attachments/assets/7ff86b5b-e1a6-4154-9ef2-585309b519d0)

Fix https://github.com/trustification/trustify-ui/issues/104

2024-07-17 14:08 UTC, carlosthe19916 requested changes
@gildub thanks for pointing this issue.
I think removing the `getSortValues` might not be a complete solution. Even if we remove it and rely on the backend the user still can click on the columns and try to sort the tables on the client side.

I have found that the reason the current sorting is not working is because I committed the mistake of using `dayjs(DATE).millisecond()`. 
- The documentation here https://day.js.org/docs/en/durations/milliseconds mentions that millisecond is a number between 0 and 999 but I wrongly assumed that the function `millisecond` would return the equivalent of :

```javascript
new Date().getTime();
```

- What about changing the current to something like:
```javascript
getSortValues: (report) => ({
  startDate: new Date(report.report.startDate).getTime(),
  endDate: new Date(report.report.endDate).getTime()
}),
```

Or alternatively we can use the `valueOf` function of dayjs https://day.js.org/docs/en/display/unix-timestamp-milliseconds
 
```javascript
getSortValues: (report) => ({
      startDate: dayjs(report.report.startDate).valueOf(),
      endDate: dayjs(report.report.startDate).valueOf(),
    }),
```

2024-07-18 09:48 UTC, gildub commented
@carlosthe19916, thanks for investigating the real issue with the sort values.
I used your latest suggestion.

2024-07-18 14:26 UTC, carlosthe19916 commented on client/src/app/pages/importer-list/importer-list.tsx
> +      endDate: dayjs(report.report.startDate).valueOf(),
```suggestion
      endDate: dayjs(report.report.endDate).valueOf(),
```

2024-07-18 14:27 UTC, carlosthe19916 commented on client/src/app/pages/importer-list/importer-list.tsx
> +      endDate: dayjs(report.report.startDate).valueOf(),
This is my own mistake. I used `startDate` in both lines. So it would be a good chance to correct my mistake

2024-07-18 14:33 UTC, carlosthe19916 approved these changes

2024-07-18 14:36 UTC, merged