Feat: implement product delete.
trustification/trustify-ui pull request #122
Opened 2024-07-24 19:08 UTC by chirino

2024-07-24 19:12 UTC, chirino commented
This is a task of https://github.com/trustification/trustify/issues/563

2024-07-26 17:34 UTC, chirino commented
mutation added.

2024-07-29 09:00 UTC, gildub requested changes
LGTM just a minor change, please see inline.

2024-07-29 09:00 UTC, gildub commented on client/src/app/queries/products.ts
> +      queryClient.invalidateQueries({queryKey: [ProductsQueryKey, id]});
The invalidateQueries key could actually be :
`queryKey: [SBOMsQueryKey]`

2024-07-29 12:38 UTC, carlosthe19916 requested changes
Thanks for the PR. The same comments done at https://github.com/trustification/trustify-ui/pull/120#pullrequestreview-2204769060 apply here

2024-08-05 23:32 UTC, chirino commented
rolled into https://github.com/trustification/trustify-ui/pull/129

2024-08-05 23:32 UTC, closed without merging