feat: Add action to delete Advisories.
trustification/trustify-ui pull request #123
Opened 2024-07-25 01:04 UTC by chirino

A task of https://github.com/trustification/trustify/issues/563

2024-07-26 16:19 UTC, gildub requested changes
Same issue here in regards of not using React Query layer for API requests.
Please update accordingly.

2024-07-29 09:01 UTC, gildub requested changes
LGTM just a minor change, please see inline

2024-07-29 09:01 UTC, gildub commented on client/src/app/queries/advisories.ts
> +      queryClient.invalidateQueries({queryKey: [AdvisoriesQueryKey, id]});
The invalidateQueries key could actually be :
`queryKey: [SBOMsQueryKey]`

2024-07-29 12:39 UTC, carlosthe19916 requested changes
Thanks for the PR. The same comments at https://github.com/trustification/trustify-ui/pull/120#pullrequestreview-2204769060 apply here

2024-08-05 23:32 UTC, chirino commented
rolled into https://github.com/trustification/trustify-ui/pull/129

2024-08-05 23:32 UTC, closed without merging