feat: Add Vulnerability delete action
trustification/trustify-ui pull request #124
Opened 2024-07-25 01:44 UTC by chirino

Task of https://github.com/trustification/trustify/issues/563

depends on https://github.com/trustification/trustify/pull/601

2024-07-26 16:20 UTC, gildub requested changes
Same issue here in regards of not using React Query layer for API requests.
Please update accordingly.

2024-07-29 09:17 UTC, gildub requested changes
LGTM just minor change, please see inline

2024-07-29 09:17 UTC, gildub commented on client/src/app/queries/vulnerabilities.ts
> +      queryClient.invalidateQueries({queryKey: [VulnerabilitiesQueryKey, id]});
The invalidateQueries key could actually be :
queryKey: [SBOMsQueryKey]

2024-07-29 12:40 UTC, carlosthe19916 requested changes
Thanks for the PR. The same comments at https://github.com/trustification/trustify-ui/pull/120#pullrequestreview-2204769060 apply here

2024-08-05 23:32 UTC, closed without merging

2024-08-05 23:32 UTC, chirino commented
rolled into https://github.com/trustification/trustify-ui/pull/129