CVE v1 parity detail enhancements
trustification/trustify-ui pull request #211
Opened 2024-11-04 17:01 UTC by kahboom

This PR is a WIP.

- [x] Update overview details for CVE
- [ ] TBD `Reserved` property
- [ ] CSS: fix spacing of properties in overview
- [x] Update tabs for Related Products -> Related CVEs
- [x] Remove Related Advisories tab
- [ ] Update column names for Related SBOMs
- [ ] Update column names for Related Advisories
- [ ] No aggregate severity showing up in column value?

## v1 Reference

https://trust.rhcloud.com/cve/content/CVE-2023-1664

![Screenshot 2024-11-04 at 3 59 47 PM](https://github.com/user-attachments/assets/25aac9b5-6a96-4214-b752-db3eec9ad3bb)

## With changes

![Screenshot 2024-11-04 at 4 59 14 PM](https://github.com/user-attachments/assets/ccd2a4fb-64db-4e86-92e7-98aad7ee64f8)

![Screenshot 2024-11-04 at 4 59 20 PM](https://github.com/user-attachments/assets/42946934-42e6-447a-90a8-878a65c9a50d)

2024-11-06 12:41 UTC, kahboom commented
WIP so far, though the UI is breaking because of several properties that were present in v1 but don't appear to exist (see [spreadsheet here](https://docs.google.com/spreadsheets/d/1mhBd3-UYvSANIXwRPDrCdGplN7cq5rQPJhIywo5mcDY/edit?gid=1088076328#gid=1088076328) for CVE Related).

Before it broke it looks like this, though I need to work on finding a better set of CVE examples/dummy data to test with:

![Screenshot 2024-11-06 at 12 20 13 PM](https://github.com/user-attachments/assets/0d88578e-bd6a-4404-aebf-98d65a0d556a)

![Screenshot 2024-11-06 at 12 21 50 PM](https://github.com/user-attachments/assets/66707645-c32b-41a8-8c64-8a7e7c5f300a)

2024-11-06 16:22 UTC, carlosthe19916 requested changes
Some minor changes we might need to consider:

- The CVE id and its severity are not horizontally aligned

![image](https://github.com/user-attachments/assets/453bd374-60be-44f0-9955-79b05a7df97a)

- The SBOMs do have a version although it is not intuitive how to get there. Perhaps you could reuse the SBOM List code

![image](https://github.com/user-attachments/assets/ebbd8774-010c-4f3e-b146-f33bbcaf2421)

- In regards of the Related SBOMs table. The table has a column "Dependencies".
  - I think that could be extracted from `/api/v1/sbom/{id}/advisory`

![image](https://github.com/user-attachments/assets/fbf4b51b-7278-4fce-b61c-0ddf0d6c3626)

- In regards of the Related Advisories table. The table has a column "Vulnerabilities".
  - I think that would be the length of the field `vulnerabilities` from the endpoint `/api/v1/advisory/{id}`

![image](https://github.com/user-attachments/assets/5aff90f2-729a-4aa8-b7e5-d16851a8b92c)

2024-11-06 18:55 UTC, kahboom commented
cheers @carlosthe19916 ! I will keep this approach in mind for the other pages

2024-11-07 14:32 UTC, kahboom commented
Thanks @carlosthe19916  I updated the PR though I'm still not seeing data for all of the fields, hopefully that's just a case of not having enough data, I will try it with Storybook in a moment but I don't think this should block the PR.

![Screenshot 2024-11-07 at 2 28 11 PM](https://github.com/user-attachments/assets/e152d272-20ea-4403-a209-f8d4012bdf3b)

![Screenshot 2024-11-07 at 2 28 20 PM](https://github.com/user-attachments/assets/c05c59dc-34e9-43ba-a567-270d0136fec7)

2024-11-07 14:43 UTC, carlosthe19916 approved these changes

2024-11-08 10:43 UTC, merged